// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace STaskManagerApi
{
    public partial class Category
    {
        public Category()
        {
            Task = new HashSet<Task>();
        }

        public int Cid { get; set; }
        public string Title { get; set; }
        public string Colour { get; set; }

        public virtual ICollection<Task> Task { get; set; }
    }
}