// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace STaskManagerLibrary
{
    public partial class STask
    {
        public STask()
        {
            Required = new HashSet<STask>();
            TaskNavigation = new HashSet<STask>();
        }

        public int Tid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateOnly Duedate { get; set; }
        public int Priority { get; set; }
        public int Account { get; set; }
        public int? Belongsto { get; set; }

        public virtual Account AccountNavigation { get; set; }
        public virtual Category BelongstoNavigation { get; set; }

        public virtual ICollection<STask> Required { get; set; }
        public virtual ICollection<STask> TaskNavigation { get; set; }
    }
}